// Copyright ⓒ 2020 Tamvana Makuluni
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the “Software”), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//! The recognized standard terminal capabilities.
macro_rules! caps {
    ($(
    $(#[$attr:meta])*
    $v:vis enum $T:ident {
        $($(#[$meta:meta])?$i:ident{$S:expr}{$(@$({$t:tt})?)?$s:expr} = $x:expr),+
        $(,@$c:ident = $cv:expr)*$(,)?
    })*) => {
        $(
            $(#[$attr])*
            $v enum $T {
                $(#[doc = "the "]
                  #[doc = $s]
                  #[doc = "capability"]
                  $(#[$meta])?
                  $i = $x
                ),+
            }
            impl $T {
                $(pub const $c: usize = $cv;)*
                pub fn from_capname(s: &str) -> Option<Self> {
                    match s {
                        $($S => Some(Self::$i),)+
                        _ => None
                    }
                }
                pub fn capname(&self) -> &'static str {
                    const CAPNAMES: &[&str] = &[$($S),+];
                    CAPNAMES[*self as usize]
                }
                pub fn from_capcode(s: &str) -> Option<Self> {
                    match s {
                        $(
                            $(#[allow(unreachable_patterns)]$($t)?)?
                            $s => Some(Self::$i),
                        )+
                        _ => None
                    }
                }
                pub fn capcode(&self) -> &'static str {
                    const CAPCODES: &[&str] = &[$($s),+];
                    CAPCODES[*self as usize]
                }
            }
            impl std::convert::TryFrom<usize> for $T {
                type Error = ();
                fn try_from(n: usize) -> Result<Self, ()> {
                    match n {
                        $($x => Ok(Self::$i),)+
                        _ => Err(())
                    }
                }
            }
        )?
    };
}
caps! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
    #[repr(usize)]
    #[doc = "The standard boolean capabilities"]
    pub enum BooleanCap {
        AutoLeftMargin{"bw"}{"bw"} = 0,
        AutoRightMargin{"am"}{"am"} = 1,
        NoEscCtlc{"xsb"}{"xb"} = 2,
        CeolStandoutGlitch{"xhp"}{"xs"} = 3,
        EatNewlineGlitch{"xenl"}{"xn"} = 4,
        EraseOverstrike{"eo"}{"eo"} = 5,
        GenericType{"gn"}{"gn"} = 6,
        HardCopy{"hc"}{"hc"} = 7,
        HasMetaKey{"km"}{"km"} = 8,
        HasStatusLine{"hs"}{"hs"} = 9,
        InsertNullGlitch{"in"}{"in"} = 10,
        MemoryAbove{"da"}{"da"} = 11,
        MemoryBelow{"db"}{"db"} = 12,
        MoveInsertMode{"mir"}{"mi"} = 13,
        MoveStandoutMode{"msgr"}{"ms"} = 14,
        OverStrike{"os"}{"os"} = 15,
        StatusLineEscOk{"eslok"}{"es"} = 16,
        DestTabsMagicSmso{"xt"}{"xt"} = 17,
        TildeGlitch{"hz"}{"hz"} = 18,
        TransparentUnderline{"ul"}{"ul"} = 19,
        XonXoff{"xon"}{"xo"} = 20,
        NeedsXonXoff{"nxon"}{"nx"} = 21,
        PrtrSilent{"mc5i"}{"5i"} = 22,
        HardCursor{"chts"}{"HC"} = 23,
        NonRevRmcup{"nrrmc"}{"NR"} = 24,
        NoPadChar{"npc"}{"NP"} = 25,
        NonDestScrollRegion{"ndscr"}{"ND"} = 26,
        CanChange{"ccc"}{"cc"} = 27,
        BackColorErase{"bce"}{"ut"} = 28,
        HueLightnessSaturation{"hls"}{"hl"} = 29,
        ColAddrGlitch{"xhpa"}{"YA"} = 30,
        CrCancelsMicroMode{"crxm"}{"YB"} = 31,
        HasPrintWheel{"daisy"}{"YC"} = 32,
        RowAddrGlitch{"xvpa"}{"YD"} = 33,
        SemiAutoRightMargin{"sam"}{"YE"} = 34,
        CpiChangesRes{"cpix"}{"YF"} = 35,
        LpiChangesRes{"lpix"}{"YG"} = 36,
        @COUNT = 37,
    }
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
    #[repr(usize)]
    #[doc = "The standard integer capabilities"]
    pub enum IntegerCap {
        Columns{"cols"}{"co"} = 0,
        InitTabs{"it"}{"it"} = 1,
        Lines{"lines"}{"li"} = 2,
        LinesOfMemory{"lm"}{"lm"} = 3,
        MagicCookieGlitch{"xmc"}{"sg"} = 4,
        PaddingBaudRate{"pb"}{"pb"} = 5,
        VirtualTerminal{"vt"}{"vt"} = 6,
        WidthStatusLine{"wsl"}{"ws"} = 7,
        NumLabels{"nlab"}{"Nl"} = 8,
        LabelHeight{"lh"}{"lh"} = 9,
        LabelWidth{"lw"}{"lw"} = 10,
        MaxAttributes{"ma"}{"ma"} = 11,
        MaximumWindows{"wnum"}{"MW"} = 12,
        MaxColors{"colors"}{"Co"} = 13,
        MaxPairs{"pairs"}{"pa"} = 14,
        NoColorVideo{"ncv"}{"NC"} = 15,
        BufferCapacity{"bufsz"}{"Ya"} = 16,
        DotVertSpacing{"spinv"}{"Yb"} = 17,
        DotHorzSpacing{"spinh"}{"Yc"} = 18,
        MaxMicroAddress{"maddr"}{"Yd"} = 19,
        MaxMicroJump{"mjump"}{"Ye"} = 20,
        MicroColSize{"mcs"}{"Yf"} = 21,
        MicroLineSize{"mls"}{"Yg"} = 22,
        NumberOfPins{"npins"}{"Yh"} = 23,
        OutputResChar{"orc"}{"Yi"} = 24,
        OutputResLine{"orl"}{"Yj"} = 25,
        OutputResHorzInch{"orhi"}{"Yk"} = 26,
        OutputResVertInch{"orvi"}{"Yl"} = 27,
        PrintRate{"cps"}{"Ym"} = 28,
        WideCharSize{"widcs"}{"Yn"} = 29,
        Buttons{"btns"}{"BT"} = 30,
        BitImageEntwining{"bitwin"}{"Yo"} = 31,
        BitImageType{"bitype"}{"Yp"} = 32,
        @COUNT = 33,
    }
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
    #[repr(usize)]
    #[doc = "The standard string capabilities"]
    pub enum StringCap {
        BackTab{"cbt"}{"bt"} = 0,
        Bell{"bel"}{"bl"} = 1,
        CarriageReturn{"cr"}{"cr"} = 2,
        ChangeScrollRegion{"csr"}{"cs"} = 3,
        ClearAllTabs{"tbc"}{"ct"} = 4,
        ClearScreen{"clear"}{"cl"} = 5,
        ClrEol{"el"}{"ce"} = 6,
        ClrEos{"ed"}{"cd"} = 7,
        ColumnAddress{"hpa"}{"ch"} = 8,
        CommandCharacter{"cmdch"}{"CC"} = 9,
        CursorAddress{"cup"}{"cm"} = 10,
        CursorDown{"cud1"}{"do"} = 11,
        CursorHome{"home"}{"ho"} = 12,
        CursorInvisible{"civis"}{"vi"} = 13,
        CursorLeft{"cub1"}{"le"} = 14,
        CursorMemAddress{"mrcup"}{"CM"} = 15,
        CursorNormal{"cnorm"}{"ve"} = 16,
        CursorRight{"cuf1"}{"nd"} = 17,
        CursorToLl{"ll"}{"ll"} = 18,
        CursorUp{"cuu1"}{"up"} = 19,
        CursorVisible{"cvvis"}{"vs"} = 20,
        DeleteCharacter{"dch1"}{"dc"} = 21,
        DeleteLine{"dl1"}{"dl"} = 22,
        DisStatusLine{"dsl"}{"ds"} = 23,
        DownHalfLine{"hd"}{"hd"} = 24,
        EnterAltCharsetMode{"smacs"}{"as"} = 25,
        EnterBlinkMode{"blink"}{"mb"} = 26,
        EnterBoldMode{"bold"}{"md"} = 27,
        EnterCaMode{"smcup"}{"ti"} = 28,
        EnterDeleteMode{"smdc"}{"dm"} = 29,
        EnterDimMode{"dim"}{"mh"} = 30,
        EnterInsertMode{"smir"}{"im"} = 31,
        EnterSecureMode{"invis"}{"mk"} = 32,
        EnterProtectedMode{"prot"}{"mp"} = 33,
        EnterReverseMode{"rev"}{"mr"} = 34,
        EnterStandoutMode{"smso"}{"so"} = 35,
        EnterUnderlineMode{"smul"}{"us"} = 36,
        EraseChars{"ech"}{"ec"} = 37,
        ExitAltCharsetMode{"rmacs"}{"ae"} = 38,
        ExitAttributeMode{"sgr0"}{"me"} = 39,
        ExitCaMode{"rmcup"}{"te"} = 40,
        ExitDeleteMode{"rmdc"}{"ed"} = 41,
        ExitInsertMode{"rmir"}{"ei"} = 42,
        ExitStandoutMode{"rmso"}{"se"} = 43,
        ExitUnderlineMode{"rmul"}{"ue"} = 44,
        FlashScreen{"flash"}{"vb"} = 45,
        FormFeed{"ff"}{"ff"} = 46,
        FromStatusLine{"fsl"}{"fs"} = 47,
        Init1string{"is1"}{"i1"} = 48,
        Init2string{"is2"}{"is"} = 49,
        Init3string{"is3"}{"i3"} = 50,
        InitFile{"if"}{"if"} = 51,
        InsertCharacter{"ich1"}{"ic"} = 52,
        InsertLine{"il1"}{"al"} = 53,
        InsertPadding{"ip"}{"ip"} = 54,
        KeyBackspace{"kbs"}{"kb"} = 55,
        KeyCatab{"ktbc"}{"ka"} = 56,
        KeyClear{"kclr"}{"kC"} = 57,
        KeyCtab{"kctab"}{"kt"} = 58,
        KeyDc{"kdch1"}{"kD"} = 59,
        KeyDl{"kdl1"}{"kL"} = 60,
        KeyDown{"kcud1"}{"kd"} = 61,
        KeyEic{"krmir"}{"kM"} = 62,
        KeyEol{"kel"}{"kE"} = 63,
        KeyEos{"ked"}{"kS"} = 64,
        KeyF0{"kf0"}{"k0"} = 65,
        KeyF1{"kf1"}{"k1"} = 66,
        KeyF10{"kf10"}{"k;"} = 67,
        KeyF2{"kf2"}{"k2"} = 68,
        KeyF3{"kf3"}{"k3"} = 69,
        KeyF4{"kf4"}{"k4"} = 70,
        KeyF5{"kf5"}{"k5"} = 71,
        KeyF6{"kf6"}{"k6"} = 72,
        KeyF7{"kf7"}{"k7"} = 73,
        KeyF8{"kf8"}{"k8"} = 74,
        KeyF9{"kf9"}{"k9"} = 75,
        KeyHome{"khome"}{"kh"} = 76,
        KeyIc{"kich1"}{"kI"} = 77,
        KeyIl{"kil1"}{"kA"} = 78,
        KeyLeft{"kcub1"}{"kl"} = 79,
        KeyLl{"kll"}{"kH"} = 80,
        KeyNpage{"knp"}{"kN"} = 81,
        KeyPpage{"kpp"}{"kP"} = 82,
        KeyRight{"kcuf1"}{"kr"} = 83,
        KeySf{"kind"}{"kF"} = 84,
        KeySr{"kri"}{"kR"} = 85,
        KeyStab{"khts"}{"kT"} = 86,
        KeyUp{"kcuu1"}{"ku"} = 87,
        KeypadLocal{"rmkx"}{"ke"} = 88,
        KeypadXmit{"smkx"}{"ks"} = 89,
        LabF0{"lf0"}{"l0"} = 90,
        LabF1{"lf1"}{"l1"} = 91,
        LabF10{"lf10"}{"la"} = 92,
        LabF2{"lf2"}{"l2"} = 93,
        LabF3{"lf3"}{"l3"} = 94,
        LabF4{"lf4"}{"l4"} = 95,
        LabF5{"lf5"}{"l5"} = 96,
        LabF6{"lf6"}{"l6"} = 97,
        LabF7{"lf7"}{"l7"} = 98,
        LabF8{"lf8"}{"l8"} = 99,
        LabF9{"lf9"}{"l9"} = 100,
        MetaOff{"rmm"}{"mo"} = 101,
        MetaOn{"smm"}{"mm"} = 102,
        Newline{"nel"}{"nw"} = 103,
        PadChar{"pad"}{"pc"} = 104,
        ParmDch{"dch"}{"DC"} = 105,
        ParmDeleteLine{"dl"}{"DL"} = 106,
        ParmDownCursor{"cud"}{"DO"} = 107,
        ParmIch{"ich"}{"IC"} = 108,
        ParmIndex{"indn"}{"SF"} = 109,
        ParmInsertLine{"il"}{"AL"} = 110,
        ParmLeftCursor{"cub"}{"LE"} = 111,
        ParmRightCursor{"cuf"}{"RI"} = 112,
        ParmRindex{"rin"}{"SR"} = 113,
        ParmUpCursor{"cuu"}{"UP"} = 114,
        PkeyKey{"pfkey"}{"pk"} = 115,
        PkeyLocal{"pfloc"}{"pl"} = 116,
        PkeyXmit{"pfx"}{"px"} = 117,
        PrintScreen{"mc0"}{"ps"} = 118,
        PrtrOff{"mc4"}{"pf"} = 119,
        PrtrOn{"mc5"}{"po"} = 120,
        RepeatChar{"rep"}{"rp"} = 121,
        Reset1string{"rs1"}{"r1"} = 122,
        Reset2string{"rs2"}{"r2"} = 123,
        Reset3string{"rs3"}{"r3"} = 124,
        ResetFile{"rf"}{"rf"} = 125,
        RestoreCursor{"rc"}{"rc"} = 126,
        RowAddress{"vpa"}{"cv"} = 127,
        SaveCursor{"sc"}{"sc"} = 128,
        ScrollForward{"ind"}{"sf"} = 129,
        ScrollReverse{"ri"}{"sr"} = 130,
        SetAttributes{"sgr"}{"sa"} = 131,
        SetTab{"hts"}{"st"} = 132,
        SetWindow{"wind"}{"wi"} = 133,
        Tab{"ht"}{"ta"} = 134,
        ToStatusLine{"tsl"}{"ts"} = 135,
        UnderlineChar{"uc"}{"uc"} = 136,
        UpHalfLine{"hu"}{"hu"} = 137,
        InitProg{"iprog"}{"iP"} = 138,
        KeyA1{"ka1"}{"K1"} = 139,
        KeyA3{"ka3"}{"K3"} = 140,
        KeyB2{"kb2"}{"K2"} = 141,
        KeyC1{"kc1"}{"K4"} = 142,
        KeyC3{"kc3"}{"K5"} = 143,
        PrtrNon{"mc5p"}{"pO"} = 144,
        CharPadding{"rmp"}{"rP"} = 145,
        AcsChars{"acsc"}{"ac"} = 146,
        PlabNorm{"pln"}{"pn"} = 147,
        KeyBtab{"kcbt"}{"kB"} = 148,
        EnterXonMode{"smxon"}{"SX"} = 149,
        ExitXonMode{"rmxon"}{"RX"} = 150,
        EnterAmMode{"smam"}{"SA"} = 151,
        ExitAmMode{"rmam"}{"RA"} = 152,
        XonCharacter{"xonc"}{"XN"} = 153,
        XoffCharacter{"xoffc"}{"XF"} = 154,
        EnaAcs{"enacs"}{"eA"} = 155,
        LabelOn{"smln"}{"LO"} = 156,
        LabelOff{"rmln"}{"LF"} = 157,
        KeyBeg{"kbeg"}{"@1"} = 158,
        KeyCancel{"kcan"}{"@2"} = 159,
        KeyClose{"kclo"}{"@3"} = 160,
        KeyCommand{"kcmd"}{"@4"} = 161,
        KeyCopy{"kcpy"}{"@5"} = 162,
        KeyCreate{"kcrt"}{"@6"} = 163,
        KeyEnd{"kend"}{"@7"} = 164,
        KeyEnter{"kent"}{"@8"} = 165,
        KeyExit{"kext"}{"@9"} = 166,
        KeyFind{"kfnd"}{"@0"} = 167,
        KeyHelp{"khlp"}{"%1"} = 168,
        KeyMark{"kmrk"}{"%2"} = 169,
        KeyMessage{"kmsg"}{"%3"} = 170,
        KeyMove{"kmov"}{"%4"} = 171,
        KeyNext{"knxt"}{"%5"} = 172,
        KeyOpen{"kopn"}{"%6"} = 173,
        KeyOptions{"kopt"}{"%7"} = 174,
        KeyPrevious{"kprv"}{"%8"} = 175,
        KeyPrint{"kprt"}{"%9"} = 176,
        KeyRedo{"krdo"}{"%0"} = 177,
        KeyReference{"kref"}{"&1"} = 178,
        KeyRefresh{"krfr"}{"&2"} = 179,
        KeyReplace{"krpl"}{"&3"} = 180,
        KeyRestart{"krst"}{"&4"} = 181,
        KeyResume{"kres"}{"&5"} = 182,
        KeySave{"ksav"}{"&6"} = 183,
        KeySuspend{"kspd"}{"&7"} = 184,
        KeyUndo{"kund"}{"&8"} = 185,
        KeySbeg{"kBEG"}{"&9"} = 186,
        KeyScancel{"kCAN"}{"&0"} = 187,
        KeyScommand{"kCMD"}{"*1"} = 188,
        KeyScopy{"kCPY"}{"*2"} = 189,
        KeyScreate{"kCRT"}{"*3"} = 190,
        KeySdc{"kDC"}{"*4"} = 191,
        KeySdl{"kDL"}{"*5"} = 192,
        KeySelect{"kslt"}{"*6"} = 193,
        KeySend{"kEND"}{"*7"} = 194,
        KeySeol{"kEOL"}{"*8"} = 195,
        KeySexit{"kEXT"}{"*9"} = 196,
        KeySfind{"kFND"}{"*0"} = 197,
        KeyShelp{"kHLP"}{"#1"} = 198,
        KeyShome{"kHOM"}{"#2"} = 199,
        KeySic{"kIC"}{"#3"} = 200,
        KeySleft{"kLFT"}{"#4"} = 201,
        KeySmessage{"kMSG"}{"%a"} = 202,
        KeySmove{"kMOV"}{"%b"} = 203,
        KeySnext{"kNXT"}{"%c"} = 204,
        KeySoptions{"kOPT"}{"%d"} = 205,
        KeySprevious{"kPRV"}{"%e"} = 206,
        KeySprint{"kPRT"}{"%f"} = 207,
        KeySredo{"kRDO"}{"%g"} = 208,
        KeySreplace{"kRPL"}{"%h"} = 209,
        KeySright{"kRIT"}{"%i"} = 210,
        KeySrsume{"kRES"}{"%j"} = 211,
        KeySsave{"kSAV"}{"!1"} = 212,
        KeySsuspend{"kSPD"}{"!2"} = 213,
        KeySundo{"kUND"}{"!3"} = 214,
        ReqForInput{"rfi"}{"RF"} = 215,
        KeyF11{"kf11"}{"F1"} = 216,
        KeyF12{"kf12"}{"F2"} = 217,
        KeyF13{"kf13"}{"F3"} = 218,
        KeyF14{"kf14"}{"F4"} = 219,
        KeyF15{"kf15"}{"F5"} = 220,
        KeyF16{"kf16"}{"F6"} = 221,
        KeyF17{"kf17"}{"F7"} = 222,
        KeyF18{"kf18"}{"F8"} = 223,
        KeyF19{"kf19"}{"F9"} = 224,
        KeyF20{"kf20"}{"FA"} = 225,
        KeyF21{"kf21"}{"FB"} = 226,
        KeyF22{"kf22"}{"FC"} = 227,
        KeyF23{"kf23"}{"FD"} = 228,
        KeyF24{"kf24"}{"FE"} = 229,
        KeyF25{"kf25"}{"FF"} = 230,
        KeyF26{"kf26"}{"FG"} = 231,
        KeyF27{"kf27"}{"FH"} = 232,
        KeyF28{"kf28"}{"FI"} = 233,
        KeyF29{"kf29"}{"FJ"} = 234,
        KeyF30{"kf30"}{"FK"} = 235,
        KeyF31{"kf31"}{"FL"} = 236,
        KeyF32{"kf32"}{"FM"} = 237,
        KeyF33{"kf33"}{"FN"} = 238,
        KeyF34{"kf34"}{"FO"} = 239,
        KeyF35{"kf35"}{"FP"} = 240,
        KeyF36{"kf36"}{"FQ"} = 241,
        KeyF37{"kf37"}{"FR"} = 242,
        KeyF38{"kf38"}{"FS"} = 243,
        KeyF39{"kf39"}{"FT"} = 244,
        KeyF40{"kf40"}{"FU"} = 245,
        KeyF41{"kf41"}{"FV"} = 246,
        KeyF42{"kf42"}{"FW"} = 247,
        KeyF43{"kf43"}{"FX"} = 248,
        KeyF44{"kf44"}{"FY"} = 249,
        KeyF45{"kf45"}{"FZ"} = 250,
        KeyF46{"kf46"}{"Fa"} = 251,
        KeyF47{"kf47"}{"Fb"} = 252,
        KeyF48{"kf48"}{"Fc"} = 253,
        KeyF49{"kf49"}{"Fd"} = 254,
        KeyF50{"kf50"}{"Fe"} = 255,
        KeyF51{"kf51"}{"Ff"} = 256,
        KeyF52{"kf52"}{"Fg"} = 257,
        KeyF53{"kf53"}{"Fh"} = 258,
        KeyF54{"kf54"}{"Fi"} = 259,
        KeyF55{"kf55"}{"Fj"} = 260,
        KeyF56{"kf56"}{"Fk"} = 261,
        KeyF57{"kf57"}{"Fl"} = 262,
        KeyF58{"kf58"}{"Fm"} = 263,
        KeyF59{"kf59"}{"Fn"} = 264,
        KeyF60{"kf60"}{"Fo"} = 265,
        KeyF61{"kf61"}{"Fp"} = 266,
        KeyF62{"kf62"}{"Fq"} = 267,
        KeyF63{"kf63"}{"Fr"} = 268,
        ClrBol{"el1"}{"cb"} = 269,
        ClearMargins{"mgc"}{"MC"} = 270,
        SetLeftMargin{"smgl"}{"ML"} = 271,
        SetRightMargin{"smgr"}{"MR"} = 272,
        LabelFormat{"fln"}{"Lf"} = 273,
        SetClock{"sclk"}{"SC"} = 274,
        DisplayClock{"dclk"}{"DK"} = 275,
        RemoveClock{"rmclk"}{"RC"} = 276,
        CreateWindow{"cwin"}{"CW"} = 277,
        GotoWindow{"wingo"}{"WG"} = 278,
        Hangup{"hup"}{"HU"} = 279,
        DialPhone{"dial"}{"DI"} = 280,
        QuickDial{"qdial"}{"QD"} = 281,
        Tone{"tone"}{"TO"} = 282,
        Pulse{"pulse"}{"PU"} = 283,
        FlashHook{"hook"}{"fh"} = 284,
        FixedPause{"pause"}{"PA"} = 285,
        WaitTone{"wait"}{"WA"} = 286,
        User0{"u0"}{"u0"} = 287,
        User1{"u1"}{"u1"} = 288,
        User2{"u2"}{"u2"} = 289,
        User3{"u3"}{"u3"} = 290,
        User4{"u4"}{"u4"} = 291,
        User5{"u5"}{"u5"} = 292,
        User6{"u6"}{"u6"} = 293,
        User7{"u7"}{"u7"} = 294,
        User8{"u8"}{"u8"} = 295,
        User9{"u9"}{"u9"} = 296,
        OrigPair{"op"}{"op"} = 297,
        OrigColors{"oc"}{"oc"} = 298,
        InitializeColor{"initc"}{"Ic"} = 299,
        InitializePair{"initp"}{"Ip"} = 300,
        SetColorPair{"scp"}{"sp"} = 301,
        SetForeground{"setf"}{"Sf"} = 302,
        SetBackground{"setb"}{"Sb"} = 303,
        ChangeCharPitch{"cpi"}{"ZA"} = 304,
        ChangeLinePitch{"lpi"}{"ZB"} = 305,
        ChangeResHorz{"chr"}{"ZC"} = 306,
        ChangeResVert{"cvr"}{"ZD"} = 307,
        DefineChar{"defc"}{"ZE"} = 308,
        EnterDoublewideMode{"swidm"}{"ZF"} = 309,
        EnterDraftQuality{"sdrfq"}{"ZG"} = 310,
        EnterItalicsMode{"sitm"}{"ZH"} = 311,
        EnterLeftwardMode{"slm"}{"ZI"} = 312,
        EnterMicroMode{"smicm"}{"ZJ"} = 313,
        EnterNearLetterQuality{"snlq"}{"ZK"} = 314,
        EnterNormalQuality{"snrmq"}{"ZL"} = 315,
        EnterShadowMode{"sshm"}{"ZM"} = 316,
        EnterSubscriptMode{"ssubm"}{"ZN"} = 317,
        EnterSuperscriptMode{"ssupm"}{"ZO"} = 318,
        EnterUpwardMode{"sum"}{"ZP"} = 319,
        ExitDoublewideMode{"rwidm"}{"ZQ"} = 320,
        ExitItalicsMode{"ritm"}{"ZR"} = 321,
        ExitLeftwardMode{"rlm"}{"ZS"} = 322,
        ExitMicroMode{"rmicm"}{"ZT"} = 323,
        ExitShadowMode{"rshm"}{"ZU"} = 324,
        ExitSubscriptMode{"rsubm"}{"ZV"} = 325,
        ExitSuperscriptMode{"rsupm"}{"ZW"} = 326,
        ExitUpwardMode{"rum"}{"ZX"} = 327,
        MicroColumnAddress{"mhpa"}{"ZY"} = 328,
        MicroDown{"mcud1"}{"ZZ"} = 329,
        MicroLeft{"mcub1"}{"Za"} = 330,
        MicroRight{"mcuf1"}{"Zb"} = 331,
        MicroRowAddress{"mvpa"}{"Zc"} = 332,
        MicroUp{"mcuu1"}{"Zd"} = 333,
        OrderOfPins{"porder"}{"Ze"} = 334,
        ParmDownMicro{"mcud"}{"Zf"} = 335,
        ParmLeftMicro{"mcub"}{"Zg"} = 336,
        ParmRightMicro{"mcuf"}{"Zh"} = 337,
        ParmUpMicro{"mcuu"}{"Zi"} = 338,
        SelectCharSet{"scs"}{"Zj"} = 339,
        SetBottomMargin{"smgb"}{"Zk"} = 340,
        SetBottomMarginParm{"smgbp"}{"Zl"} = 341,
        SetLeftMarginParm{"smglp"}{"Zm"} = 342,
        SetRightMarginParm{"smgrp"}{"Zn"} = 343,
        SetTopMargin{"smgt"}{"Zo"} = 344,
        SetTopMarginParm{"smgtp"}{"Zp"} = 345,
        StartBitImage{"sbim"}{"Zq"} = 346,
        StartCharSetDef{"scsd"}{"Zr"} = 347,
        StopBitImage{"rbim"}{"Zs"} = 348,
        StopCharSetDef{"rcsd"}{"Zt"} = 349,
        SubscriptCharacters{"subcs"}{"Zu"} = 350,
        SuperscriptCharacters{"supcs"}{"Zv"} = 351,
        TheseCauseCr{"docr"}{"Zw"} = 352,
        ZeroMotion{"zerom"}{"Zx"} = 353,
        CharSetNames{"csnm"}{"Zy"} = 354,
        KeyMouse{"kmous"}{"Km"} = 355,
        MouseInfo{"minfo"}{"Mi"} = 356,
        ReqMousePos{"reqmp"}{"RQ"} = 357,
        GetMouse{"getm"}{"Gm"} = 358,
        SetAForeground{"setab"}{"AB"} = 359,
        SetABackground{"setaf"}{"AF"} = 360,
        PkeyPlab{"pfxl"}{"xl"} = 361,
        DeviceType{"devt"}{"dv"} = 362,
        CodeSetInit{"csin"}{"ci"} = 363,
        Set0DesSeq{"s0ds"}{"s0"} = 364,
        Set1DesSeq{"s1ds"}{"s1"} = 365,
        Set2DesSeq{"s2ds"}{"s2"} = 366,
        Set3DesSeq{"s3ds"}{"s3"} = 367,
        SetLrMargin{"smglr"}{@"ML"} = 368,
        SetTbMargin{"smgtb"}{"MT"} = 369,
        BitImageRepeat{"birep"}{"Xy"} = 370,
        BitImageNewline{"binel"}{"Zz"} = 371,
        BitImageCarriageReturn{"bicr"}{"Yv"} = 372,
        ColorNames{"colornm"}{"Yw"} = 373,
        DefineBitImageRegion{"defbi"}{"Yx"} = 374,
        EndBitImageRegion{"endbi"}{"Yy"} = 375,
        SetColorBand{"setcolor"}{"Yz"} = 376,
        SetPageLength{"slines"}{"YZ"} = 377,
        DisplayPcChar{"dispc"}{"S1"} = 378,
        EnterPcCharsetMode{"smpch"}{"S2"} = 379,
        ExitPcCharsetMode{"rmpch"}{"S3"} = 380,
        EnterScancodeMode{"smsc"}{"S4"} = 381,
        ExitScancodeMode{"rmsc"}{"S5"} = 382,
        PcTermOptions{"pctrm"}{"S6"} = 383,
        ScancodeEscape{"scesc"}{"S7"} = 384,
        AltScancodeEsc{"scesa"}{"S8"} = 385,
        EnterHorizontalHlMode{"ehhlm"}{"Xh"} = 386,
        EnterLeftHlMode{"elhlm"}{"Xl"} = 387,
        EnterLowHlMode{"elohlm"}{"Xo"} = 388,
        EnterRightHlMode{"erhlm"}{"Xr"} = 389,
        EnterTopHlMode{"ethlm"}{"Xt"} = 390,
        EnterVerticalHlMode{"evhlm"}{"Xv"} = 391,
        SetAAttributes{"sgr1"}{"sA"} = 392,
        SetPglenInch{"slength"}{"YI"} = 393,
        @COUNT = 394,
    }
}
